name: ascii_x
description: Cross-platform image to ASCII art generator app.
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: ^7.2.0
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"               # Must include #
  image: assets/splash/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scale_aspect_fill

